name: Doxygen

on:
  push:
    branches:
      - main  # Run workflow on push to main branch

jobs:
  doxygen:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive  # Fetch submodules if any

      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Generate Doxygen documentation
        run: doxygen Doxyfile
        
      #- name: Move files to root
      #  run: |
      #    shopt -s dotglob  # Include hidden files in the move
      #    mv html/* .      # Move the contents of 'html' to the current directory
      #    shopt -u dotglob  # Reset the dotglob option
      #    rmdir html         # Remove the now-empty 'html' directory

      #- name: Deploy to GitHub Pages
      #  uses: JamesIves/github-pages-deploy-action@v4
      #  with:
      #    folder: html  # Output folder of Doxygen
      #    branch: gh-pages  # Branch to deploy to
      #    token: ${{ secrets.DEPLOY_TOKEN }}  # Use the secret


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          # Default Doxyfile build documentation to html directory. 
          # Change the directory if changes in Doxyfile
          branch: gh-pages  # Branch to deploy to
          publish_dir: ./html
